- label: ":semgrep: Semgrep Full Scan"
  commands:
    - export SEMGREP_COMMIT=$${BUILDKITE_COMMIT}
    - export SEMGREP_BRANCH=$${BUILDKITE_BRANCH}
    - export SEMGREP_REPO_URL=$${BUILDKITE_REPO}
    - export SEMGREP_REPO_NAME="$$(echo "$$BUILDKITE_REPO" | sed -e 's#git@github.com:##' | sed -e 's#.git##')"
    - echo "${BUILDKITE_BRANCH}"
    - echo "${BUILDKITE_COMMIT}"
    - echo "${BUILDKITE_BRANCH}"
    - echo "${BUILDKITE_REPO}"
    - echo "Semgrep Token: $SEMGREP_APP_TOKEN"
    - semgrep ci
  if: |
    build.pull_request.id == null

  plugins:
    - docker#v5.11.0:
        image: semgrep/semgrep:latest
        environment:
          # The following variable is required to set up a scan connected to Semgrep AppSec Platform:
          - SEMGREP_APP_TOKEN: "676a288a3a67e0ed5ba59c635196b93c10deb216ac089508d1437ff59f0830e8"
