- label: ":semgrep: Semgrep Full Scan"
  commands:
    - if [[ $BUILDKITE_COMMIT =~ ^[a-fA-F0-9]{40}$ ]]; then export SEMGREP_COMMIT=${BUILDKITE_COMMIT}; fi
    - semgrep ci
  if: |
    build.pull_request.id == null
    
  plugins:
    - docker#v5.11.0:
        image: semgrep/semgrep:latest
        environment:
          # The following variable is required to set up a scan connected to Semgrep AppSec Platform:
          - "SEMGREP_APP_TOKEN"
