- label: ":semgrep: Semgrep Full Scan"
  plugins:
    - docker#v5.11.0:
        image: semgrep/semgrep:latest
        environment:
          # The following variable is required to set up a scan connected to Semgrep AppSec Platform:
          - "SEMGREP_APP_TOKEN"
